### ISSUE TITLE
[issue]: Ubuntu autoinstall using cloudinit crashes subiquity

### ISSUE THREAD

**Issue by nwmcsween** [ventoy/Ventoy#1947]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

Sandisk

### Image file download link (if applicable)

https://releases.ubuntu.com/22.10/ubuntu-22.10-live-server-amd64.iso

### What happened?

Autoinstall fails as subiquity runs dmsetup info/dev/dm-0 as /dev/dm-0 isn't actually a device in ventoy due to how ventoy boots isos.

**Comment by nwmcsween** [comment]
Relevant user-data
```yaml
#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: true
  identity:
    hostname: helium
    password: addpasswd
    realname: nwm
    username: nwm
  ssh:
    allow-pw: false
    install-server: true
  storage:
    layout:
      name: direct
  packages:
    - haveged
    - less
    - tmux
    - vim
  kernel:
    flavor: hwe
  timezone: geoip
  updates: all

```

**Comment by ventoy** [comment]
Yes. 
So when you use cloudinit  autoinstall with Ventoy, you have to specify the disk in the `storage` section as follows:

```
#cloud-config
autoinstall:
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
    - arches: [amd64, i386]
      uri: http://archive.ubuntu.com/ubuntu
    - arches: [default]
      uri: http://ports.ubuntu.com/ubuntu-ports
  identity: {hostname: public, password: $6$76eU//YqTyV7foup$8xcQQLxVXixZGQ5WMbFD7BArZ2F8w8F.KkmJRyKsJpama.44/xlk.axi0MMWiLSFEERFnUqCWLsSPumCCmjQL/, realname: public, username: public}
  keyboard: {layout: us, toggle: null, variant: ''}
  locale: en_US  
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    config:
    - {ptable: gpt, path: /dev/sdb, wipe: superblock-recursive, preserve: false, name: '', grub_device: true, type: disk, id: disk-sdb}
    - {device: disk-sdb, size: 1048576, flag: bios_grub, number: 1, preserve: false, type: partition, id: partition-0}
    - {device: disk-sdb, size: 21471690752, wipe: superblock, flag: '', number: 2, preserve: false, type: partition, id: partition-1}
    - {fstype: ext4, volume: partition-1, preserve: false, type: format, id: format-0}
    - {device: format-0, path: /, type: mount, id: mount-0}
  version: 1

```
